version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cineverse-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cineverse
    ports:
      - "3306:3306"
    networks:
      - cineverse-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cineverse-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cineverse
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - cineverse-network
    # LÃ­mite de memoria para evitar cuelgues en t3.micro
    deploy:
      resources:
        limits:
          memory: 768M

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cineverse-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cineverse-network
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  cineverse-network:
    driver: bridge